version: "3.6"

services:
  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./config.yml:/config.yml:ro

  # access with
  # curl -v whoami0-192.168.57.101.nip.io
  whoami:
    image: "containous/whoami"
    container_name: "whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami0-192.168.57.101.nip.io`)"
      - "traefik.http.routers.whoami.entrypoints=web"
