---
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: true
  file:
    filename: /config.yml
entryPoints:
  web:
    address: ":80"
  whoami_8181:
    address: ":8181"